# -*- coding: utf-8 -*-

"""
    weatherapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from weatherapi.decorators import lazy_property
from weatherapi.configuration import Configuration
from weatherapi.controllers.ap_is_controller import APIsController


class WeatherapiClient(object):

    config = Configuration

    @lazy_property
    def ap_is(self):
        return APIsController()


    def __init__(self,
                 key=None):
        if key is not None:
            Configuration.key = key

