# -*- coding: utf-8 -*-

"""
    weatherapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import weatherapi.models.location
import weatherapi.models.astronomy

class AstronomyJsonResponse(object):

    """Implementation of the 'AstronomyJson Response' model.

    TODO: type model description here.

    Attributes:
        location (Location): TODO: type description here.
        astronomy (Astronomy): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "location":'location',
        "astronomy":'astronomy'
    }

    def __init__(self,
                 location=None,
                 astronomy=None):
        """Constructor for the AstronomyJsonResponse class"""

        # Initialize members of the class
        self.location = location
        self.astronomy = astronomy


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        location = weatherapi.models.location.Location.from_dictionary(dictionary.get('location')) if dictionary.get('location') else None
        astronomy = weatherapi.models.astronomy.Astronomy.from_dictionary(dictionary.get('astronomy')) if dictionary.get('astronomy') else None

        # Return an object of this model
        return cls(location,
                   astronomy)


