# -*- coding: utf-8 -*-

"""
    weatherapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import weatherapi.models.astro

class Astronomy(object):

    """Implementation of the 'Astronomy' model.

    TODO: type model description here.

    Attributes:
        astro (Astro): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "astro":'astro'
    }

    def __init__(self,
                 astro=None):
        """Constructor for the Astronomy class"""

        # Initialize members of the class
        self.astro = astro


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        astro = weatherapi.models.astro.Astro.from_dictionary(dictionary.get('astro')) if dictionary.get('astro') else None

        # Return an object of this model
        return cls(astro)


